version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: vugpt_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vugpt
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vugpt_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
